### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by chenscottus** [fan23j/yolov7-pose-whole-body#1]
Hello,

    Could you please share your trained models?

    Many thanks!

-Scott

**Comment by fan23j** [comment]
Hello, there is actually a bug in the repo rn (wrong flip indices). But I can probably get you the yolov7tiny weights sometime this weekend.

**Comment by chenscottus** [comment]
Many thanks!       Best Regards,- ScottOn Mar 31, 2023, at 6:04 PM, Jack Fan ***@***.***> wrote:﻿
Hello, there is actually a bug in the repo rn (wrong flip indices). But I can probably get you the yolov7tiny weights sometime this weekend.

**Comment by fan23j** [comment]
Hi Scott, the model is taking longer to converge than i initially anticipated. But will update you as soon as the quality is ok.

**Comment by fan23j** [comment]
Hey Scott, I just updated the README with a link to the yolov7-tiny weights. I also included two mosaics of the labels + predictions. Let me know if this helps with your use-case at all. Also since the server I use cannot connect to github, there may be minor discrepancies between this repo and the working one. Let me know if you need anything else!

**Comment by chenscottus** [comment]
Great! I will try it. Many thanks! Scott
